spring:
  application:
    name: service-gateway

  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/users/**

        - id: service-catalogs
          uri: lb://SERVICE-CATALOG
          predicates:
            - Path=/catalogs/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
