spring:
  application:
    name: SERVICE-GATEWAY

  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce
    gateway:
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}

        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: service-catalog
          uri: lb://SERVICE-CATALOG
          predicates:
            - Path=/catalogs/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/catalogs(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: service-catalog
          uri: lb://SERVICE-CATALOG
          predicates:
            - Path=/catalogs/**
          filters:
            - RewritePath=/catalogs(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/orders/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/orders(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
