feign:
  client:
    url:
      jsonPlaceHolder: https://jsonplaceholder.typicode.com

    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    io.github.shirohoo.openfeign.client: DEBUG

