feign:
  client:
    url:
      # url ???? /? ??? ??? ??????? @GetMapping("/post") ?? ??
      # url ???? /? ??? ??????? @GetMapping("post") ?? ??
      jsonPlaceHolder: https://jsonplaceholder.typicode.com
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
