server:
  port: 8888

spring:
  application:
    name: SERVICE-CONFIG

  cloud:
    config:
      server:
        git:
          uri: file://D:\git-configuration\spring-cloud-ecommerce
          search-paths: spring-cloud-ecommerce
#          username: your username
#          password: your password
