server:
  port: 8888

spring:
  application:
    name: SERVICE-CONFIG

  cloud:
    config:
      server:
        git:
          uri: https://github.com/shirohoo/spring-cloud-examples.git
          search-paths: spring-cloud-ecommerce
#          username: your username
#          password: your password
