server:
  port: 9002

spring:
  application:
    name: catalog-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:38080/eureka
